name: Build

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - v*.*.*           # Push events to v1.0, v1.1, and v1.9 tags

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-14]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'
          channel: 'stable'
          cache: false
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: dart pub global activate flutter_distributor
      - run: flutter pub get
      - if: matrix.os == 'macos-14'
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          npm install -g appdmg
          dart run scripts/init.dart -a 'arm64'
          flutter_distributor release --name ${{ matrix.os }}
          mv dist/${VERSION}/lux-${VERSION}+${VERSION}-macos.dmg dist/${VERSION}/lux-${VERSION}-arm64-macos.dmg
          dart run scripts/init.dart -a 'amd64'
          flutter_distributor release --name ${{ matrix.os }}
          mv dist/${VERSION}/lux-${VERSION}+${VERSION}-macos.dmg dist/${VERSION}/lux-${VERSION}-amd64-macos.dmg

      - if: matrix.os == 'windows-latest'
        run: |
          dart run scripts/init.dart
          flutter_distributor release --name ${{ matrix.os }}

      - uses: actions/upload-artifact@v3
        with:
          name: artifact
          path: dist/*/*


  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3

      - name: Generate checksum
        uses: jmgilman/actions-generate-checksum@v1
        with:
          patterns: |
            artifact/*/*

      - name: GH Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            checksum.txt
            artifact/*/*